<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html >
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Reporte de pruebas</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.1"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="https://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="https://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap");
    :root{
        --body-font: 'Poppins', sans-serif;

    }
    body{
        margin: var(--header-height) 0 0 0;
        padding: 1rem 1rem 0;
        font-family: var(--body-font);
        background-color: #F9F6FD;
    }    
    .container{
        background-color: white;
        border-radius: 3%;
    }
    .imagenpwst img{
        position:static;
        right: 4%;
        padding-top: 5%;
    }

/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<div class="imagenpwst">
    <img src="https://i.postimg.cc/g2fdS2VC/Recurso-jpg.jpg"width="320"  align="right" >
</div>    
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
4:Error  
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = 'Hola';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2 || level ==4) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    detail_class=document.getElementsByClassName('detail');
    //console.log(detail_class.length)
    if (level == 3) {
        for (var i = 0; i < detail_class.length; i++){
            detail_class[i].innerHTML="Ver"
        }
    }
    else{
            for (var i = 0; i < detail_class.length; i++){
            detail_class[i].innerHTML="Ocultar"
        }
    }
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {

        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];

        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "Ver"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "Ocultar"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&');
    s = s.replace(/</g,'<');
    s = s.replace(/>/g,'>');
    return s;
}
</script>
<div class='heading'>
<h2 style="font-family: Microsoft YaHei">Reporte de pruebas</h4>
<p class='attribute'><strong>Desarrollado por : </strong> Area de Testing PWST</p>
<p class='attribute'><strong>Fecha y hora de inicio : </strong> 2023-04-20 18:40:35</p>
<p class='attribute'><strong>Duracion : </strong> 0:02:03.723834</p>
<p class='attribute'><strong>Resultado : </strong> Total 8，Correctos 1 ，Errores 7 ，Taza de resultado 12.50%</p>

<h3 class='description'>Detalles</h3>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>Resumen 12.50% </a>
<a class="btn btn-warning" href='javascript:showCase(4)'>Errores 7 </a>
<a class="btn btn-danger" href='javascript:showCase(1)'>Fallidos 0 </a>
<a class="btn btn-success" href='javascript:showCase(2)'>Correctos 1 </a>
<a class="btn btn-info" href='javascript:showCase(3)'>Test realizados 8 </a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 14px;">
    <td>Caso de Prueba</td>
    <td>Total</td>
    <td>Correctos</td>
    <td>Fallido</td>
    <td>Error</td>
    <td>Detalles</td>
    <td>Captura del error</td>
</tr>

<tr class='errorClass warning'>
    <td>PerfilesMoviles.Test: Escenario 1 de Perfiles Moviles</td>
    <td class="text-center">8</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">7</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',8)" class="detail" id='c1'>Detalles</a></td>
    <td class="text-center"></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>Error</button>
    <div id='div_ft1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>Error</button>
    <div id='div_ft1_1' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_1: 2023-04-20 18:40:37,894 - root - INFO -  Se abre el chrome
2023-04-20 18:40:41,780 - root - INFO -  Entra a la URL
2023-04-20 18:40:42,156 - root - INFO -  Maximiza la pantalla
Traceback (most recent call last):
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="mainFrame"]"}
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0091DCE3+50899]
	(No symbol) [0x008AE111]
	(No symbol) [0x007B5588]
	(No symbol) [0x007E08F9]
	(No symbol) [0x007E0AFB]
	(No symbol) [0x0080F902]
	(No symbol) [0x007FB944]
	(No symbol) [0x0080E01C]
	(No symbol) [0x007FB6F6]
	(No symbol) [0x007D7708]
	(No symbol) [0x007D886D]
	GetHandleVerifier [0x00B83EAE+2566302]
	GetHandleVerifier [0x00BB92B1+2784417]
	GetHandleVerifier [0x00BB327C+2759788]
	GetHandleVerifier [0x009B5740+672048]
	(No symbol) [0x008B8872]
	(No symbol) [0x008B41C8]
	(No symbol) [0x008B42AB]
	(No symbol) [0x008A71B7]
	BaseThreadInitThunk [0x76047D49+25]
	RtlInitializeExceptionChain [0x772CB74B+107]
	RtlClearBits [0x772CB6CF+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="mainFrame"]"}
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0091DCE3+50899]
	(No symbol) [0x008AE111]
	(No symbol) [0x007B5588]
	(No symbol) [0x007E08F9]
	(No symbol) [0x007E0AFB]
	(No symbol) [0x0080F902]
	(No symbol) [0x007FB944]
	(No symbol) [0x0080E01C]
	(No symbol) [0x007FB6F6]
	(No symbol) [0x007D7708]
	(No symbol) [0x007D886D]
	GetHandleVerifier [0x00B83EAE+2566302]
	GetHandleVerifier [0x00BB92B1+2784417]
	GetHandleVerifier [0x00BB327C+2759788]
	GetHandleVerifier [0x009B5740+672048]
	(No symbol) [0x008B8872]
	(No symbol) [0x008B41C8]
	(No symbol) [0x008B42AB]
	(No symbol) [0x008A71B7]
	BaseThreadInitThunk [0x76047D49+25]
	RtlInitializeExceptionChain [0x772CB74B+107]
	RtlClearBits [0x772CB6CF+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\PerfilesMoviles.py", line 31, in test
    self.driver.switch_to.frame("mainFrame")
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference)
selenium.common.exceptions.NoSuchFrameException: Message: mainFrame



    </pre>
    </div>
    </td>
    <td align="right">
        <a hidden="hidden" href="" target="_blank">
            <img src="" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='pt1_2' class='hiddenRow'>
    <td class='passCase' width='300px'><div class='testcase'>test_000: Ingresa a la base de datos</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_2' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_2'>Correcto</button>
    <div id='div_pt1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_2' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_pt1_2'>Correcto</button>
    <div id='div_pt1_2' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
pt1_2: 2023-04-20 18:40:45,308 - root - INFO -  Escribe el usuario
2023-04-20 18:40:45,483 - root - INFO -  Escribe la contraseña
2023-04-20 18:40:45,665 - root - INFO -  Se dio clic en el boton ingresar
2023-04-20 18:40:47,063 - root - INFO -  Ejecutar Enterprise
2023-04-20 18:40:51,130 - root - INFO -  Cambia entre pestañas


    </pre>
    </div>
    </td>
    <td align="right">
        <a hidden="hidden" href="" target="_blank">
            <img src="" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_001: Abre menu y ejecuta pantalla</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>Error</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>Error</button>
    <div id='div_ft1_3' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_3: 2023-04-20 18:41:54,980 - root - ERROR - No se pudo ingresar por medio del buscador, revise si el xpath sigue siendo el mismo, para mas detalles del error consulte el reporte
2023-04-20 18:41:54,981 - root - INFO -  Captura: C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\report\img  screen：20230420_18_41_54.png
2023-04-20 18:41:55,142 - root - INFO -  La función buscador funciona de manera correcta.
2023-04-20 18:42:24,160 - root - ERROR - La pantalla ejecutada no es correcta, validar que la acción anterior haya finalizado, que el nombre de la pantalla sea el correcto o que la página no presente lentitud
2023-04-20 18:42:27,162 - root - INFO -  Captura: C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\report\img  screen：20230420_18_42_27.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\ingresopantalla.py", line 56, in ingresopantalla
    Pantalla = self.wait.until(conditions.visibility((By.XPATH, Configuracion.titulo_pantalla))).text
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0091DCE3+50899]
	(No symbol) [0x008AE111]
	(No symbol) [0x007B5588]
	(No symbol) [0x0079D333]
	(No symbol) [0x007FF4DB]
	(No symbol) [0x0080DB33]
	(No symbol) [0x007FB6F6]
	(No symbol) [0x007D7708]
	(No symbol) [0x007D886D]
	GetHandleVerifier [0x00B83EAE+2566302]
	GetHandleVerifier [0x00BB92B1+2784417]
	GetHandleVerifier [0x00BB327C+2759788]
	GetHandleVerifier [0x009B5740+672048]
	(No symbol) [0x008B8872]
	(No symbol) [0x008B41C8]
	(No symbol) [0x008B42AB]
	(No symbol) [0x008A71B7]
	BaseThreadInitThunk [0x76047D49+25]
	RtlInitializeExceptionChain [0x772CB74B+107]
	RtlClearBits [0x772CB6CF+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\PerfilesMoviles.py", line 43, in test_001
    success = ingresopantalla.ingresopantalla.ingresopantalla(self, conditions, Configuracion)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\ingresopantalla.py", line 70, in ingresopantalla
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 929, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 965, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode("ascii"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 977, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0091DCE3+50899]
	(No symbol) [0x008AE111]
	(No symbol) [0x007B5588]
	(No symbol) [0x0079D333]
	(No symbol) [0x007FF4DB]
	(No symbol) [0x0080DB33]
	(No symbol) [0x007FB6F6]
	(No symbol) [0x007D7708]
	(No symbol) [0x007D886D]
	GetHandleVerifier [0x00B83EAE+2566302]
	GetHandleVerifier [0x00BB92B1+2784417]
	GetHandleVerifier [0x00BB327C+2759788]
	GetHandleVerifier [0x009B5740+672048]
	(No symbol) [0x008B8872]
	(No symbol) [0x008B41C8]
	(No symbol) [0x008B42AB]
	(No symbol) [0x008A71B7]
	BaseThreadInitThunk [0x76047D49+25]
	RtlInitializeExceptionChain [0x772CB74B+107]
	RtlClearBits [0x772CB6CF+191]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20230420_18_42_27.png" target="_blank">
            <img src="../../../../img/20230420_18_42_27.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_002: Abre la ventana de nuevo y crear un registro</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>Error</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>Error</button>
    <div id='div_ft1_4' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_4: 2023-04-20 18:42:27,182 - root - ERROR - La pantalla ejecutada no es correcta, validar que la acción anterior haya finalizado, que el nombre de la pantalla sea el correcto o que la página no presente lentitud
2023-04-20 18:42:30,184 - root - INFO -  Captura: C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\report\img  screen：20230420_18_42_30.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\nuevoregistro.py", line 18, in nuevoregistro
    Crea = self.wait.until(conditions.visibility((By.XPATH, Configuracion.titulo_nuevo))).text
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0091DCE3+50899]
	(No symbol) [0x008AE111]
	(No symbol) [0x007B5588]
	(No symbol) [0x0079D333]
	(No symbol) [0x007FF4DB]
	(No symbol) [0x0080DB33]
	(No symbol) [0x007FB6F6]
	(No symbol) [0x007D7708]
	(No symbol) [0x007D886D]
	GetHandleVerifier [0x00B83EAE+2566302]
	GetHandleVerifier [0x00BB92B1+2784417]
	GetHandleVerifier [0x00BB327C+2759788]
	GetHandleVerifier [0x009B5740+672048]
	(No symbol) [0x008B8872]
	(No symbol) [0x008B41C8]
	(No symbol) [0x008B42AB]
	(No symbol) [0x008A71B7]
	BaseThreadInitThunk [0x76047D49+25]
	RtlInitializeExceptionChain [0x772CB74B+107]
	RtlClearBits [0x772CB6CF+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\PerfilesMoviles.py", line 57, in test_002
    success = nuevoregistro.nuevoregistro.nuevoregistro(self, conditions, Configuracion)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\nuevoregistro.py", line 28, in nuevoregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 929, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 965, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode("ascii"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 977, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0091DCE3+50899]
	(No symbol) [0x008AE111]
	(No symbol) [0x007B5588]
	(No symbol) [0x0079D333]
	(No symbol) [0x007FF4DB]
	(No symbol) [0x0080DB33]
	(No symbol) [0x007FB6F6]
	(No symbol) [0x007D7708]
	(No symbol) [0x007D886D]
	GetHandleVerifier [0x00B83EAE+2566302]
	GetHandleVerifier [0x00BB92B1+2784417]
	GetHandleVerifier [0x00BB327C+2759788]
	GetHandleVerifier [0x009B5740+672048]
	(No symbol) [0x008B8872]
	(No symbol) [0x008B41C8]
	(No symbol) [0x008B42AB]
	(No symbol) [0x008A71B7]
	BaseThreadInitThunk [0x76047D49+25]
	RtlInitializeExceptionChain [0x772CB74B+107]
	RtlClearBits [0x772CB6CF+191]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20230420_18_42_30.png" target="_blank">
            <img src="../../../../img/20230420_18_42_30.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_5' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_003: Repite el Registro</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_5' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_5'>Error</button>
    <div id='div_ft1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_5' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_5'>Error</button>
    <div id='div_ft1_5' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_5: 2023-04-20 18:42:30,199 - root - ERROR - No se dió click en el botón Refrescar, validar que la acción anterior haya finalizado, que el xpath sea el correcto o que la página no presente lentitud 
2023-04-20 18:42:33,201 - root - INFO -  Captura: C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\report\img  screen：20230420_18_42_33.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\repetirregistro.py", line 19, in repetirregistro
    Refresca = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_Refresca)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0091DCE3+50899]
	(No symbol) [0x008AE111]
	(No symbol) [0x007B5588]
	(No symbol) [0x0079D333]
	(No symbol) [0x007FF4DB]
	(No symbol) [0x0080DB33]
	(No symbol) [0x007FB6F6]
	(No symbol) [0x007D7708]
	(No symbol) [0x007D886D]
	GetHandleVerifier [0x00B83EAE+2566302]
	GetHandleVerifier [0x00BB92B1+2784417]
	GetHandleVerifier [0x00BB327C+2759788]
	GetHandleVerifier [0x009B5740+672048]
	(No symbol) [0x008B8872]
	(No symbol) [0x008B41C8]
	(No symbol) [0x008B42AB]
	(No symbol) [0x008A71B7]
	BaseThreadInitThunk [0x76047D49+25]
	RtlInitializeExceptionChain [0x772CB74B+107]
	RtlClearBits [0x772CB6CF+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\PerfilesMoviles.py", line 73, in test_003
    success = repetirregistro.repetirregistro.repetirregistro(self, conditions, Configuracion)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\repetirregistro.py", line 30, in repetirregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 929, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 965, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode("ascii"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 977, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0091DCE3+50899]
	(No symbol) [0x008AE111]
	(No symbol) [0x007B5588]
	(No symbol) [0x0079D333]
	(No symbol) [0x007FF4DB]
	(No symbol) [0x0080DB33]
	(No symbol) [0x007FB6F6]
	(No symbol) [0x007D7708]
	(No symbol) [0x007D886D]
	GetHandleVerifier [0x00B83EAE+2566302]
	GetHandleVerifier [0x00BB92B1+2784417]
	GetHandleVerifier [0x00BB327C+2759788]
	GetHandleVerifier [0x009B5740+672048]
	(No symbol) [0x008B8872]
	(No symbol) [0x008B41C8]
	(No symbol) [0x008B42AB]
	(No symbol) [0x008A71B7]
	BaseThreadInitThunk [0x76047D49+25]
	RtlInitializeExceptionChain [0x772CB74B+107]
	RtlClearBits [0x772CB6CF+191]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20230420_18_42_33.png" target="_blank">
            <img src="../../../../img/20230420_18_42_33.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_004: Modificar el registro</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>Error</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>Error</button>
    <div id='div_ft1_6' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_6: 2023-04-20 18:42:33,214 - root - ERROR - No se dió click en el botón Refrescar, validar que la acción anterior haya finalizado, que el xpath sea el correcto o que la página no presente lentitud
2023-04-20 18:42:36,217 - root - INFO -  Captura: C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\report\img  screen：20230420_18_42_36.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\modificarregistro.py", line 19, in modificarregistro
    Refresca2 = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_Refresca)))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0091DCE3+50899]
	(No symbol) [0x008AE111]
	(No symbol) [0x007B5588]
	(No symbol) [0x0079D333]
	(No symbol) [0x007FF4DB]
	(No symbol) [0x0080DB33]
	(No symbol) [0x007FB6F6]
	(No symbol) [0x007D7708]
	(No symbol) [0x007D886D]
	GetHandleVerifier [0x00B83EAE+2566302]
	GetHandleVerifier [0x00BB92B1+2784417]
	GetHandleVerifier [0x00BB327C+2759788]
	GetHandleVerifier [0x009B5740+672048]
	(No symbol) [0x008B8872]
	(No symbol) [0x008B41C8]
	(No symbol) [0x008B42AB]
	(No symbol) [0x008A71B7]
	BaseThreadInitThunk [0x76047D49+25]
	RtlInitializeExceptionChain [0x772CB74B+107]
	RtlClearBits [0x772CB6CF+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\PerfilesMoviles.py", line 101, in test_004
    success = modificarregistro.modificarregistro.modificarregistro(self, conditions, Configuracion)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\modificarregistro.py", line 30, in modificarregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 929, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 965, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode("ascii"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 977, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0091DCE3+50899]
	(No symbol) [0x008AE111]
	(No symbol) [0x007B5588]
	(No symbol) [0x0079D333]
	(No symbol) [0x007FF4DB]
	(No symbol) [0x0080DB33]
	(No symbol) [0x007FB6F6]
	(No symbol) [0x007D7708]
	(No symbol) [0x007D886D]
	GetHandleVerifier [0x00B83EAE+2566302]
	GetHandleVerifier [0x00BB92B1+2784417]
	GetHandleVerifier [0x00BB327C+2759788]
	GetHandleVerifier [0x009B5740+672048]
	(No symbol) [0x008B8872]
	(No symbol) [0x008B41C8]
	(No symbol) [0x008B42AB]
	(No symbol) [0x008A71B7]
	BaseThreadInitThunk [0x76047D49+25]
	RtlInitializeExceptionChain [0x772CB74B+107]
	RtlClearBits [0x772CB6CF+191]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20230420_18_42_36.png" target="_blank">
            <img src="../../../../img/20230420_18_42_36.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_7' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_005: Eliminar el registro creado</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_7' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_7'>Error</button>
    <div id='div_ft1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_7' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_7'>Error</button>
    <div id='div_ft1_7' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_7: 2023-04-20 18:42:36,227 - root - ERROR - No se dió click en el botón Refrescar, validar que la acción anterior haya finalizado, que el xpath sea el correcto o que la página no presente lentitud
2023-04-20 18:42:39,228 - root - INFO -  Captura: C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\report\img  screen：20230420_18_42_39.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\eliminarregistro.py", line 18, in eliminarregistro
    Refresca3 = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_Refresca)))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0091DCE3+50899]
	(No symbol) [0x008AE111]
	(No symbol) [0x007B5588]
	(No symbol) [0x0079D333]
	(No symbol) [0x007FF4DB]
	(No symbol) [0x0080DB33]
	(No symbol) [0x007FB6F6]
	(No symbol) [0x007D7708]
	(No symbol) [0x007D886D]
	GetHandleVerifier [0x00B83EAE+2566302]
	GetHandleVerifier [0x00BB92B1+2784417]
	GetHandleVerifier [0x00BB327C+2759788]
	GetHandleVerifier [0x009B5740+672048]
	(No symbol) [0x008B8872]
	(No symbol) [0x008B41C8]
	(No symbol) [0x008B42AB]
	(No symbol) [0x008A71B7]
	BaseThreadInitThunk [0x76047D49+25]
	RtlInitializeExceptionChain [0x772CB74B+107]
	RtlClearBits [0x772CB6CF+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\PerfilesMoviles.py", line 129, in test_005
    success = eliminarregistro.eliminarregistro.eliminarregistro(self, conditions, Configuracion)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\eliminarregistro.py", line 29, in eliminarregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 929, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 965, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode("ascii"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 977, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0091DCE3+50899]
	(No symbol) [0x008AE111]
	(No symbol) [0x007B5588]
	(No symbol) [0x0079D333]
	(No symbol) [0x007FF4DB]
	(No symbol) [0x0080DB33]
	(No symbol) [0x007FB6F6]
	(No symbol) [0x007D7708]
	(No symbol) [0x007D886D]
	GetHandleVerifier [0x00B83EAE+2566302]
	GetHandleVerifier [0x00BB92B1+2784417]
	GetHandleVerifier [0x00BB327C+2759788]
	GetHandleVerifier [0x009B5740+672048]
	(No symbol) [0x008B8872]
	(No symbol) [0x008B41C8]
	(No symbol) [0x008B42AB]
	(No symbol) [0x008A71B7]
	BaseThreadInitThunk [0x76047D49+25]
	RtlInitializeExceptionChain [0x772CB74B+107]
	RtlClearBits [0x772CB6CF+191]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20230420_18_42_39.png" target="_blank">
            <img src="../../../../img/20230420_18_42_39.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_8' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_006: Cerrar_Navegador</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_8' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_8'>Error</button>
    <div id='div_ft1_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_8' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_8'>Error</button>
    <div id='div_ft1_8' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_8: Traceback (most recent call last):
  File "C:\xampp\htdocs\versiones\automatizaciones\AutoPWST\01PM\testCase\PerfilesMoviles.py", line 147, in test_006
    self.driver.close()
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 561, in close
    self.execute(Command.CLOSE)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0091DCE3+50899]
	(No symbol) [0x008AE111]
	(No symbol) [0x007B5588]
	(No symbol) [0x007A70CB]
	(No symbol) [0x007A778A]
	(No symbol) [0x007A7728]
	(No symbol) [0x0079C37A]
	(No symbol) [0x0079CBD7]
	(No symbol) [0x00803C48]
	(No symbol) [0x007FB8C3]
	(No symbol) [0x007D7708]
	(No symbol) [0x007D886D]
	GetHandleVerifier [0x00B83EAE+2566302]
	GetHandleVerifier [0x00BB92B1+2784417]
	GetHandleVerifier [0x00BB327C+2759788]
	GetHandleVerifier [0x009B5740+672048]
	(No symbol) [0x008B8872]
	(No symbol) [0x008B41C8]
	(No symbol) [0x008B42AB]
	(No symbol) [0x008A71B7]
	BaseThreadInitThunk [0x76047D49+25]
	RtlInitializeExceptionChain [0x772CB74B+107]
	RtlClearBits [0x772CB6CF+191]



    </pre>
    </div>
    </td>
    <td align="right">
        <a hidden="hidden" href="" target="_blank">
            <img src="" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>Caso de prueba</td>
    <td>8</td>
    <td>1</td>
    <td>0</td>
    <td>7</td>
    <td>Taza de resultado：12.50%</td>
    <td> <a href="" target="_blank"></a></td>
</tr>
</table>

<div id='ending'> </div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
