<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html >
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Reporte de pruebas</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.1"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="https://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="https://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap");
    :root{
        --body-font: 'Poppins', sans-serif;

    }
    body{
        margin: var(--header-height) 0 0 0;
        padding: 1rem 1rem 0;
        font-family: var(--body-font);
        background-color: #F9F6FD;
    }    
    .container{
        background-color: white;
        border-radius: 3%;
    }
    .imagenpwst img{
        position:static;
        right: 4%;
        padding-top: 5%;
    }

/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<div class="imagenpwst">
    <img src="https://i.postimg.cc/g2fdS2VC/Recurso-jpg.jpg"width="320"  align="right" >
</div>    
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
4:Error  
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = 'Hola';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2 || level ==4) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    detail_class=document.getElementsByClassName('detail');
    //console.log(detail_class.length)
    if (level == 3) {
        for (var i = 0; i < detail_class.length; i++){
            detail_class[i].innerHTML="Ver"
        }
    }
    else{
            for (var i = 0; i < detail_class.length; i++){
            detail_class[i].innerHTML="Ocultar"
        }
    }
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {

        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];

        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "Ver"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "Ocultar"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&');
    s = s.replace(/</g,'<');
    s = s.replace(/>/g,'>');
    return s;
}
</script>
<div class='heading'>
<h2 style="font-family: Microsoft YaHei">Reporte de pruebas</h4>
<p class='attribute'><strong>Desarrollado por : </strong> Area de Testing PWST</p>
<p class='attribute'><strong>Fecha y hora de inicio : </strong> 2022-09-12 11:48:35</p>
<p class='attribute'><strong>Duracion : </strong> 0:01:59.758203</p>
<p class='attribute'><strong>Resultado : </strong> Total 8，Errores 8 ，Taza de resultado 0.00%</p>

<h3 class='description'>Detalles</h3>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>Resumen 0.00% </a>
<a class="btn btn-warning" href='javascript:showCase(4)'>Errores 8 </a>
<a class="btn btn-danger" href='javascript:showCase(1)'>Fallidos 0 </a>
<a class="btn btn-success" href='javascript:showCase(2)'>Correctos 0 </a>
<a class="btn btn-info" href='javascript:showCase(3)'>Test realizados 8 </a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 14px;">
    <td>Caso de Prueba</td>
    <td>Total</td>
    <td>Correctos</td>
    <td>Fallido</td>
    <td>Error</td>
    <td>Detalles</td>
    <td>Captura del error</td>
</tr>

<tr class='errorClass warning'>
    <td>ClasificacionArticulo.Test: Escenarios de Clasificación de Artículos 1</td>
    <td class="text-center">8</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">8</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',8)" class="detail" id='c1'>Detalles</a></td>
    <td class="text-center"></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>Error</button>
    <div id='div_ft1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>Error</button>
    <div id='div_ft1_1' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_1: 2022-09-12 11:48:36,683 - root - INFO -  Se abre el chrome
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\ClasificacionArticulo.py", line 25, in test
    self.driver.get(configgnral.URL)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 436, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from disconnected: unable to send message to renderer
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x007F78B3+2193587]
	Ordinal0 [0x00790681+1771137]
	Ordinal0 [0x006A41A8+803240]
	Ordinal0 [0x0069608B+745611]
	Ordinal0 [0x00696498+746648]
	Ordinal0 [0x006A0610+787984]
	Ordinal0 [0x0069781D+751645]
	Ordinal0 [0x00698450+754768]
	Ordinal0 [0x00697A2A+752170]
	Ordinal0 [0x00696FAF+749487]
	Ordinal0 [0x00695E94+745108]
	Ordinal0 [0x0069636D+746349]
	Ordinal0 [0x006A5974+809332]
	Ordinal0 [0x006FE18D+1171853]
	Ordinal0 [0x006ED7AC+1103788]
	Ordinal0 [0x006FDAE2+1170146]
	Ordinal0 [0x006ED5C6+1103302]
	Ordinal0 [0x006C77E0+948192]
	Ordinal0 [0x006C86E6+952038]
	GetHandleVerifier [0x00AA0CB2+2738370]
	GetHandleVerifier [0x00A921B8+2678216]
	GetHandleVerifier [0x008817AA+512954]
	GetHandleVerifier [0x00880856+509030]
	Ordinal0 [0x0079743B+1799227]
	Ordinal0 [0x0079BB68+1817448]
	Ordinal0 [0x0079BC55+1817685]
	Ordinal0 [0x007A5230+1856048]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a hidden="hidden" href="" target="_blank">
            <img src="" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_000: Ingresa a la base de datos</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>Error</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>Error</button>
    <div id='div_ft1_2' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_2: 2022-09-12 11:48:50,336 - root - ERROR - No se pudo encontrar el campo para ingresar el usuario, revise si el xpath sigue siendo el mismo, para mas detalles del error consulte el reporte
2022-09-12 11:48:50,338 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\report\img  screen：20220912_11_48_50.png
Traceback (most recent call last):
  File "C:/xampp/htdocs/Versiones/automatizaciones/AutoPWST/ingresologin.py", line 26, in ingresologin
    Usuario = self.wait.until(conditions.visibility((By.XPATH, configgnral.id_usuario)))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x007F78B3+2193587]
	Ordinal0 [0x00790681+1771137]
	Ordinal0 [0x006A4070+802928]
	Ordinal0 [0x00699AB2+760498]
	Ordinal0 [0x0068CEAF+708271]
	Ordinal0 [0x00691142+725314]
	Ordinal0 [0x006955C9+742857]
	Ordinal0 [0x006A5500+808192]
	Ordinal0 [0x006FD2C2+1168066]
	Ordinal0 [0x006ED5C6+1103302]
	Ordinal0 [0x006C77E0+948192]
	Ordinal0 [0x006C86E6+952038]
	GetHandleVerifier [0x00AA0CB2+2738370]
	GetHandleVerifier [0x00A921B8+2678216]
	GetHandleVerifier [0x008817AA+512954]
	GetHandleVerifier [0x00880856+509030]
	Ordinal0 [0x0079743B+1799227]
	Ordinal0 [0x0079BB68+1817448]
	Ordinal0 [0x0079BC55+1817685]
	Ordinal0 [0x007A5230+1856048]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\ClasificacionArticulo.py", line 36, in test_000
    return ingresologin.ingresologin(self)
  File "C:/xampp/htdocs/Versiones/automatizaciones/AutoPWST/ingresologin.py", line 35, in ingresologin
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x007F78B3+2193587]
	Ordinal0 [0x00790681+1771137]
	Ordinal0 [0x006A4070+802928]
	Ordinal0 [0x00699AB2+760498]
	Ordinal0 [0x0068CEAF+708271]
	Ordinal0 [0x00691142+725314]
	Ordinal0 [0x006955C9+742857]
	Ordinal0 [0x006A5500+808192]
	Ordinal0 [0x006FD2C2+1168066]
	Ordinal0 [0x006ED5C6+1103302]
	Ordinal0 [0x006C77E0+948192]
	Ordinal0 [0x006C86E6+952038]
	GetHandleVerifier [0x00AA0CB2+2738370]
	GetHandleVerifier [0x00A921B8+2678216]
	GetHandleVerifier [0x008817AA+512954]
	GetHandleVerifier [0x00880856+509030]
	Ordinal0 [0x0079743B+1799227]
	Ordinal0 [0x0079BB68+1817448]
	Ordinal0 [0x0079BC55+1817685]
	Ordinal0 [0x007A5230+1856048]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20220912_11_48_50.png" target="_blank">
            <img src="../../../../img/20220912_11_48_50.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_001: Abre menu y ejecuta pantalla</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>Error</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>Error</button>
    <div id='div_ft1_3' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_3: Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\ClasificacionArticulo.py", line 40, in test_001
    return ingresopantalla.ingresopantalla(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\ingresopantalla.py", line 19, in ingresopantalla
    btn_cierrasesionactiva = self.driver.find_element(By.XPATH, "//button[@class = 'p-continuebutton']")
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x007F78B3+2193587]
	Ordinal0 [0x00790681+1771137]
	Ordinal0 [0x006A4070+802928]
	Ordinal0 [0x00699AB2+760498]
	Ordinal0 [0x0068CEAF+708271]
	Ordinal0 [0x00691142+725314]
	Ordinal0 [0x006955C9+742857]
	Ordinal0 [0x006A5500+808192]
	Ordinal0 [0x006FD2C2+1168066]
	Ordinal0 [0x006ED5C6+1103302]
	Ordinal0 [0x006C77E0+948192]
	Ordinal0 [0x006C86E6+952038]
	GetHandleVerifier [0x00AA0CB2+2738370]
	GetHandleVerifier [0x00A921B8+2678216]
	GetHandleVerifier [0x008817AA+512954]
	GetHandleVerifier [0x00880856+509030]
	Ordinal0 [0x0079743B+1799227]
	Ordinal0 [0x0079BB68+1817448]
	Ordinal0 [0x0079BC55+1817685]
	Ordinal0 [0x007A5230+1856048]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a hidden="hidden" href="" target="_blank">
            <img src="" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_002: Abre la ventana de nuevo y crear un registro</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>Error</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>Error</button>
    <div id='div_ft1_4' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_4: 2022-09-12 11:49:21,590 - root - ERROR - La pantalla ejecutada no es correcta, validar que la acción anterior haya finalizado,que el xpath sea el correcto o que la página no presente lentitud
2022-09-12 11:49:21,592 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\report\img  screen：20220912_11_49_21.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\nuevoregistro.py", line 20, in nuevoregistro
    Crea = self.wait.until(conditions.visibility((By.XPATH, Configuracion.titulo_nuevo))).text
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x007F78B3+2193587]
	Ordinal0 [0x00790681+1771137]
	Ordinal0 [0x006A4070+802928]
	Ordinal0 [0x00699AB2+760498]
	Ordinal0 [0x0068CEAF+708271]
	Ordinal0 [0x00691142+725314]
	Ordinal0 [0x006955C9+742857]
	Ordinal0 [0x006A5500+808192]
	Ordinal0 [0x006FD2C2+1168066]
	Ordinal0 [0x006ED5C6+1103302]
	Ordinal0 [0x006C77E0+948192]
	Ordinal0 [0x006C86E6+952038]
	GetHandleVerifier [0x00AA0CB2+2738370]
	GetHandleVerifier [0x00A921B8+2678216]
	GetHandleVerifier [0x008817AA+512954]
	GetHandleVerifier [0x00880856+509030]
	Ordinal0 [0x0079743B+1799227]
	Ordinal0 [0x0079BB68+1817448]
	Ordinal0 [0x0079BC55+1817685]
	Ordinal0 [0x007A5230+1856048]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\ClasificacionArticulo.py", line 44, in test_002
    return nuevoregistro.nuevoregistro(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\nuevoregistro.py", line 30, in nuevoregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x007F78B3+2193587]
	Ordinal0 [0x00790681+1771137]
	Ordinal0 [0x006A4070+802928]
	Ordinal0 [0x00699AB2+760498]
	Ordinal0 [0x0068CEAF+708271]
	Ordinal0 [0x00691142+725314]
	Ordinal0 [0x006955C9+742857]
	Ordinal0 [0x006A5500+808192]
	Ordinal0 [0x006FD2C2+1168066]
	Ordinal0 [0x006ED5C6+1103302]
	Ordinal0 [0x006C77E0+948192]
	Ordinal0 [0x006C86E6+952038]
	GetHandleVerifier [0x00AA0CB2+2738370]
	GetHandleVerifier [0x00A921B8+2678216]
	GetHandleVerifier [0x008817AA+512954]
	GetHandleVerifier [0x00880856+509030]
	Ordinal0 [0x0079743B+1799227]
	Ordinal0 [0x0079BB68+1817448]
	Ordinal0 [0x0079BC55+1817685]
	Ordinal0 [0x007A5230+1856048]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20220912_11_49_21.png" target="_blank">
            <img src="../../../../img/20220912_11_49_21.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_5' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_003: Repetir el registro creado anteriormente</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_5' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_5'>Error</button>
    <div id='div_ft1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_5' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_5'>Error</button>
    <div id='div_ft1_5' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_5: 2022-09-12 11:49:42,446 - root - ERROR - No se dio click el botón Refrescar, validar que la acción anterior haya finalizado,que el xpath sea el correcto o que la página no presente lentitud
2022-09-12 11:49:42,448 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\report\img  screen：20220912_11_49_42.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\repetirregistro.py", line 21, in repetirregistro
    Refresca = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_Refresca)))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x007F78B3+2193587]
	Ordinal0 [0x00790681+1771137]
	Ordinal0 [0x006A4070+802928]
	Ordinal0 [0x00699AB2+760498]
	Ordinal0 [0x0068CEAF+708271]
	Ordinal0 [0x00691142+725314]
	Ordinal0 [0x006955C9+742857]
	Ordinal0 [0x006A5500+808192]
	Ordinal0 [0x006FD2C2+1168066]
	Ordinal0 [0x006ED5C6+1103302]
	Ordinal0 [0x006C77E0+948192]
	Ordinal0 [0x006C86E6+952038]
	GetHandleVerifier [0x00AA0CB2+2738370]
	GetHandleVerifier [0x00A921B8+2678216]
	GetHandleVerifier [0x008817AA+512954]
	GetHandleVerifier [0x00880856+509030]
	Ordinal0 [0x0079743B+1799227]
	Ordinal0 [0x0079BB68+1817448]
	Ordinal0 [0x0079BC55+1817685]
	Ordinal0 [0x007A5230+1856048]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\ClasificacionArticulo.py", line 48, in test_003
    return repetirregistro.repetirregistro(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\repetirregistro.py", line 32, in repetirregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x007F78B3+2193587]
	Ordinal0 [0x00790681+1771137]
	Ordinal0 [0x006A4070+802928]
	Ordinal0 [0x00699AB2+760498]
	Ordinal0 [0x0068CEAF+708271]
	Ordinal0 [0x00691142+725314]
	Ordinal0 [0x006955C9+742857]
	Ordinal0 [0x006A5500+808192]
	Ordinal0 [0x006FD2C2+1168066]
	Ordinal0 [0x006ED5C6+1103302]
	Ordinal0 [0x006C77E0+948192]
	Ordinal0 [0x006C86E6+952038]
	GetHandleVerifier [0x00AA0CB2+2738370]
	GetHandleVerifier [0x00A921B8+2678216]
	GetHandleVerifier [0x008817AA+512954]
	GetHandleVerifier [0x00880856+509030]
	Ordinal0 [0x0079743B+1799227]
	Ordinal0 [0x0079BB68+1817448]
	Ordinal0 [0x0079BC55+1817685]
	Ordinal0 [0x007A5230+1856048]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20220912_11_49_42.png" target="_blank">
            <img src="../../../../img/20220912_11_49_42.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_004: Modificar el registro</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>Error</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>Error</button>
    <div id='div_ft1_6' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_6: 2022-09-12 11:50:03,304 - root - ERROR - No se dio click al botón Refrescar, validar que la acción anterior haya finalizado,que el xpath sea el correcto o que la página no presente lentitud
2022-09-12 11:50:03,306 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\report\img  screen：20220912_11_50_03.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\modificarregistro.py", line 21, in modificarregistro
    Refresca2 = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_Refresca)))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x007F78B3+2193587]
	Ordinal0 [0x00790681+1771137]
	Ordinal0 [0x006A4070+802928]
	Ordinal0 [0x00699AB2+760498]
	Ordinal0 [0x0068CEAF+708271]
	Ordinal0 [0x00691142+725314]
	Ordinal0 [0x006955C9+742857]
	Ordinal0 [0x006A5500+808192]
	Ordinal0 [0x006FD2C2+1168066]
	Ordinal0 [0x006ED5C6+1103302]
	Ordinal0 [0x006C77E0+948192]
	Ordinal0 [0x006C86E6+952038]
	GetHandleVerifier [0x00AA0CB2+2738370]
	GetHandleVerifier [0x00A921B8+2678216]
	GetHandleVerifier [0x008817AA+512954]
	GetHandleVerifier [0x00880856+509030]
	Ordinal0 [0x0079743B+1799227]
	Ordinal0 [0x0079BB68+1817448]
	Ordinal0 [0x0079BC55+1817685]
	Ordinal0 [0x007A5230+1856048]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\ClasificacionArticulo.py", line 52, in test_004
    return modificarregistro.modificarregistro(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\modificarregistro.py", line 32, in modificarregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x007F78B3+2193587]
	Ordinal0 [0x00790681+1771137]
	Ordinal0 [0x006A4070+802928]
	Ordinal0 [0x00699AB2+760498]
	Ordinal0 [0x0068CEAF+708271]
	Ordinal0 [0x00691142+725314]
	Ordinal0 [0x006955C9+742857]
	Ordinal0 [0x006A5500+808192]
	Ordinal0 [0x006FD2C2+1168066]
	Ordinal0 [0x006ED5C6+1103302]
	Ordinal0 [0x006C77E0+948192]
	Ordinal0 [0x006C86E6+952038]
	GetHandleVerifier [0x00AA0CB2+2738370]
	GetHandleVerifier [0x00A921B8+2678216]
	GetHandleVerifier [0x008817AA+512954]
	GetHandleVerifier [0x00880856+509030]
	Ordinal0 [0x0079743B+1799227]
	Ordinal0 [0x0079BB68+1817448]
	Ordinal0 [0x0079BC55+1817685]
	Ordinal0 [0x007A5230+1856048]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20220912_11_50_03.png" target="_blank">
            <img src="../../../../img/20220912_11_50_03.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_7' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_005: Eliminar el registro creado</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_7' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_7'>Error</button>
    <div id='div_ft1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_7' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_7'>Error</button>
    <div id='div_ft1_7' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_7: 2022-09-12 11:50:24,178 - root - ERROR - No se dio click al botón Refrescar, validar que la acción anterior haya finalizado,que el xpath sea el correcto o que la página no presente lentitud
2022-09-12 11:50:24,179 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\report\img  screen：20220912_11_50_24.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\eliminarregistro.py", line 20, in eliminarregistro
    Refresca3 = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_Refresca)))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x007F78B3+2193587]
	Ordinal0 [0x00790681+1771137]
	Ordinal0 [0x006A4070+802928]
	Ordinal0 [0x00699AB2+760498]
	Ordinal0 [0x0068CEAF+708271]
	Ordinal0 [0x00691142+725314]
	Ordinal0 [0x006955C9+742857]
	Ordinal0 [0x006A5500+808192]
	Ordinal0 [0x006FD2C2+1168066]
	Ordinal0 [0x006ED5C6+1103302]
	Ordinal0 [0x006C77E0+948192]
	Ordinal0 [0x006C86E6+952038]
	GetHandleVerifier [0x00AA0CB2+2738370]
	GetHandleVerifier [0x00A921B8+2678216]
	GetHandleVerifier [0x008817AA+512954]
	GetHandleVerifier [0x00880856+509030]
	Ordinal0 [0x0079743B+1799227]
	Ordinal0 [0x0079BB68+1817448]
	Ordinal0 [0x0079BC55+1817685]
	Ordinal0 [0x007A5230+1856048]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\ClasificacionArticulo.py", line 56, in test_005
    return eliminarregistro.eliminarregistro(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\eliminarregistro.py", line 31, in eliminarregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x007F78B3+2193587]
	Ordinal0 [0x00790681+1771137]
	Ordinal0 [0x006A4070+802928]
	Ordinal0 [0x00699AB2+760498]
	Ordinal0 [0x0068CEAF+708271]
	Ordinal0 [0x00691142+725314]
	Ordinal0 [0x006955C9+742857]
	Ordinal0 [0x006A5500+808192]
	Ordinal0 [0x006FD2C2+1168066]
	Ordinal0 [0x006ED5C6+1103302]
	Ordinal0 [0x006C77E0+948192]
	Ordinal0 [0x006C86E6+952038]
	GetHandleVerifier [0x00AA0CB2+2738370]
	GetHandleVerifier [0x00A921B8+2678216]
	GetHandleVerifier [0x008817AA+512954]
	GetHandleVerifier [0x00880856+509030]
	Ordinal0 [0x0079743B+1799227]
	Ordinal0 [0x0079BB68+1817448]
	Ordinal0 [0x0079BC55+1817685]
	Ordinal0 [0x007A5230+1856048]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/20220912_11_50_24.png" target="_blank">
            <img src="../../../../img/20220912_11_50_24.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_8' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_006: Cerrar_Navegador</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_8' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_8'>Error</button>
    <div id='div_ft1_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_8' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_8'>Error</button>
    <div id='div_ft1_8' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_8: Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01CLA\testCase\ClasificacionArticulo.py", line 60, in test_006
    self.driver.close()
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 937, in close
    self.execute(Command.CLOSE)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\desarrollo testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
	Ordinal0 [0x007F78B3+2193587]
	Ordinal0 [0x00790681+1771137]
	Ordinal0 [0x006A4070+802928]
	Ordinal0 [0x00699AB2+760498]
	Ordinal0 [0x0068C440+705600]
	Ordinal0 [0x006F3BC0+1129408]
	Ordinal0 [0x006ED773+1103731]
	Ordinal0 [0x006C77E0+948192]
	Ordinal0 [0x006C86E6+952038]
	GetHandleVerifier [0x00AA0CB2+2738370]
	GetHandleVerifier [0x00A921B8+2678216]
	GetHandleVerifier [0x008817AA+512954]
	GetHandleVerifier [0x00880856+509030]
	Ordinal0 [0x0079743B+1799227]
	Ordinal0 [0x0079BB68+1817448]
	Ordinal0 [0x0079BC55+1817685]
	Ordinal0 [0x007A5230+1856048]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a hidden="hidden" href="" target="_blank">
            <img src="" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>Caso de prueba</td>
    <td>8</td>
    <td>0</td>
    <td>0</td>
    <td>8</td>
    <td>Taza de resultado：0.00%</td>
    <td> <a href="" target="_blank"></a></td>
</tr>
</table>

<div id='ending'> </div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
