<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html >
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Reporte de pruebas</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.1"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="https://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="https://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap");
    :root{
        --body-font: 'Poppins', sans-serif;

    }
    body{
        margin: var(--header-height) 0 0 0;
        padding: 1rem 1rem 0;
        font-family: var(--body-font);
        background-color: #F9F6FD;
    }    
    .container{
        background-color: white;
        border-radius: 3%;
    }
    .imagenpwst img{
        position:static;
        right: 4%;
        padding-top: 5%;
    }

/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<div class="imagenpwst">
    <img src="https://i.postimg.cc/g2fdS2VC/Recurso-jpg.jpg"width="320"  align="right" >
</div>    
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
4:Error  
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = 'Hola';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2 || level ==4) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    detail_class=document.getElementsByClassName('detail');
    //console.log(detail_class.length)
    if (level == 3) {
        for (var i = 0; i < detail_class.length; i++){
            detail_class[i].innerHTML="Ver"
        }
    }
    else{
            for (var i = 0; i < detail_class.length; i++){
            detail_class[i].innerHTML="Ocultar"
        }
    }
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {

        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];

        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "Ver"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "Ocultar"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&');
    s = s.replace(/</g,'<');
    s = s.replace(/>/g,'>');
    return s;
}
</script>
<div class='heading'>
<h2 style="font-family: Microsoft YaHei">Reporte de pruebas</h4>
<p class='attribute'><strong>Desarrollado por : </strong> Area de Testing PWST</p>
<p class='attribute'><strong>Fecha y hora de inicio : </strong> 2022-07-04 14:31:24</p>
<p class='attribute'><strong>Duracion : </strong> 0:03:35.390994</p>
<p class='attribute'><strong>Resultado : </strong> Total 9，Correctos 1 ，Errores 8 ，Taza de resultado 11.11%</p>

<h3 class='description'>Detalles</h3>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>Resumen 11.11% </a>
<a class="btn btn-warning" href='javascript:showCase(4)'>Errores 8 </a>
<a class="btn btn-danger" href='javascript:showCase(1)'>Fallidos 0 </a>
<a class="btn btn-success" href='javascript:showCase(2)'>Correctos 1 </a>
<a class="btn btn-info" href='javascript:showCase(3)'>Test realizados 9 </a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 14px;">
    <td>Caso de Prueba</td>
    <td>Total</td>
    <td>Correctos</td>
    <td>Fallido</td>
    <td>Error</td>
    <td>Detalles</td>
    <td>Captura del error</td>
</tr>

<tr class='errorClass warning'>
    <td>TiposPopup.Test: Escenario 1 de Tipos de PopUp</td>
    <td class="text-center">9</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">8</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',9)" class="detail" id='c1'>Detalles</a></td>
    <td class="text-center"></td>
</tr>

<tr id='pt1_1' class='hiddenRow'>
    <td class='passCase' width='300px'><div class='testcase'>test</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_1' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_1'>Correcto</button>
    <div id='div_pt1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_1' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_pt1_1'>Correcto</button>
    <div id='div_pt1_1' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
pt1_1: 2022-07-04 14:31:25,985 - root - INFO -  Se abre el chrome
2022-07-04 14:31:29,574 - root - INFO -  Entra a la URL
2022-07-04 14:31:29,693 - root - INFO -  Maximiza la pantalla
2022-07-04 14:31:32,737 - root - INFO -  Cambia al frame


    </pre>
    </div>
    </td>
    <td align="right">
        <a hidden="hidden" href="" target="_blank">
            <img src="" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_000: Ingresa a la base de datos</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>Error</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>Error</button>
    <div id='div_ft1_2' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_2: 2022-07-04 14:31:35,801 - root - INFO -  Escribe el usuario
2022-07-04 14:31:35,876 - root - INFO -  Escribe la contraseña
2022-07-04 14:31:35,962 - root - INFO -  Se dio clic en el boton ingresar
2022-07-04 14:31:51,155 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\report\img  screen：20220704_14_31_51.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\TiposPopup.py", line 38, in test_000
    return ingresologin.ingresologin(self)
  File "C:/xampp/htdocs/Versiones/automatizaciones/AutoPWST/ingresologin.py", line 69, in ingresologin
    Enterprise = self.wait.until(conditions.visibility((By.XPATH, configgnral.btn_Enterprise)))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563D78+802168]
	Ordinal0 [0x00591880+989312]
	Ordinal0 [0x00591B1B+989979]
	Ordinal0 [0x005BE912+1173778]
	Ordinal0 [0x005AC824+1099812]
	Ordinal0 [0x005BCC22+1166370]
	Ordinal0 [0x005AC5F6+1099254]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/ 20220704_14_31_51.png" target="_blank">
            <img src="../../../../img/ 20220704_14_31_51.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_001: Elimina Error de inicio</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>Error</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>Error</button>
    <div id='div_ft1_3' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_3: 2022-07-04 14:32:45,445 - root - ERROR - No se encontró el botón Cerrar Error, revise si el xpath sigue siendo el mismo, para mas detalles del error consulte el reporte
2022-07-04 14:32:45,447 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\report\img  screen：20220704_14_32_45.png
Traceback (most recent call last):
  File "C:/xampp/htdocs/Versiones/automatizaciones/AutoPWST/Errorinicio.py", line 17, in Errorinicio
    Cerrarerror = self.wait.until(conditions.visibility((By.XPATH, btn_cerrar_error)))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563C40+801856]
	Ordinal0 [0x00558932+756018]
	Ordinal0 [0x00559168+758120]
	Ordinal0 [0x0055AA22+764450]
	Ordinal0 [0x00554379+738169]
	Ordinal0 [0x005650D0+807120]
	Ordinal0 [0x005BC402+1164290]
	Ordinal0 [0x005AC5F6+1099254]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\TiposPopup.py", line 42, in test_001
    return Errorinicio.Errorinicio(self)
  File "C:/xampp/htdocs/Versiones/automatizaciones/AutoPWST/Errorinicio.py", line 28, in Errorinicio
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563C40+801856]
	Ordinal0 [0x00558932+756018]
	Ordinal0 [0x00559168+758120]
	Ordinal0 [0x0055AA22+764450]
	Ordinal0 [0x00554379+738169]
	Ordinal0 [0x005650D0+807120]
	Ordinal0 [0x005BC402+1164290]
	Ordinal0 [0x005AC5F6+1099254]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/ 20220704_14_32_45.png" target="_blank">
            <img src="../../../../img/ 20220704_14_32_45.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_002: Abre menu y ejecuta pantalla</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>Error</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>Error</button>
    <div id='div_ft1_4' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_4: 2022-07-04 14:33:09,763 - root - ERROR - No se pudo encontrar el botón para desplegar el menu completo, revise si el xpath sigue siendo el mismo, para mas detalles del error consulte el reporte
2022-07-04 14:33:09,765 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\report\img  screen：20220704_14_33_09.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\ingresopantalla.py", line 18, in ingresopantalla
    Sandwich = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_sandwich)))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563C40+801856]
	Ordinal0 [0x00558932+756018]
	Ordinal0 [0x00559168+758120]
	Ordinal0 [0x0055AA22+764450]
	Ordinal0 [0x00554379+738169]
	Ordinal0 [0x005650D0+807120]
	Ordinal0 [0x005BC402+1164290]
	Ordinal0 [0x005AC5F6+1099254]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\TiposPopup.py", line 46, in test_002
    return ingresopantalla.ingresopantalla(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\ingresopantalla.py", line 29, in ingresopantalla
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563C40+801856]
	Ordinal0 [0x00558932+756018]
	Ordinal0 [0x00559168+758120]
	Ordinal0 [0x0055AA22+764450]
	Ordinal0 [0x00554379+738169]
	Ordinal0 [0x005650D0+807120]
	Ordinal0 [0x005BC402+1164290]
	Ordinal0 [0x005AC5F6+1099254]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/ 20220704_14_33_09.png" target="_blank">
            <img src="../../../../img/ 20220704_14_33_09.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_5' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_003: Abre la ventana de nuevo y crear un registro</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_5' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_5'>Error</button>
    <div id='div_ft1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_5' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_5'>Error</button>
    <div id='div_ft1_5' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_5: 2022-07-04 14:33:34,104 - root - ERROR - La pantalla ejecutada no es correcta, revise si el xpath sigue siendo el mismo, para mas detalles del error consulte el reporte
2022-07-04 14:33:34,106 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\report\img  screen：20220704_14_33_34.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\nuevoregistro.py", line 20, in nuevoregistro
    Crea = self.wait.until(conditions.visibility((By.XPATH, Configuracion.titulo_nuevo))).text
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563C40+801856]
	Ordinal0 [0x00558932+756018]
	Ordinal0 [0x00559168+758120]
	Ordinal0 [0x0055AA22+764450]
	Ordinal0 [0x00554379+738169]
	Ordinal0 [0x005650D0+807120]
	Ordinal0 [0x005BC402+1164290]
	Ordinal0 [0x005AC5F6+1099254]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\TiposPopup.py", line 50, in test_003
    return nuevoregistro.nuevoregistro(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\nuevoregistro.py", line 30, in nuevoregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563C40+801856]
	Ordinal0 [0x00558932+756018]
	Ordinal0 [0x00559168+758120]
	Ordinal0 [0x0055AA22+764450]
	Ordinal0 [0x00554379+738169]
	Ordinal0 [0x005650D0+807120]
	Ordinal0 [0x005BC402+1164290]
	Ordinal0 [0x005AC5F6+1099254]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/ 20220704_14_33_34.png" target="_blank">
            <img src="../../../../img/ 20220704_14_33_34.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_004: Repetir el registro creado anteriormente</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>Error</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>Error</button>
    <div id='div_ft1_6' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_6: 2022-07-04 14:33:58,473 - root - ERROR - No se encontró el botón Refrescar, revise si el xpath sigue siendo el mismo, para mas detalles del error consulte el reporte
2022-07-04 14:33:58,474 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\report\img  screen：20220704_14_33_58.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\repetirregistro.py", line 21, in repetirregistro
    Refresca = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_Refresca)))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563C40+801856]
	Ordinal0 [0x00558932+756018]
	Ordinal0 [0x00559168+758120]
	Ordinal0 [0x0055AA22+764450]
	Ordinal0 [0x00554379+738169]
	Ordinal0 [0x005650D0+807120]
	Ordinal0 [0x005BC402+1164290]
	Ordinal0 [0x005AC5F6+1099254]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\TiposPopup.py", line 54, in test_004
    return repetirregistro.repetirregistro(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\repetirregistro.py", line 32, in repetirregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563C40+801856]
	Ordinal0 [0x00558932+756018]
	Ordinal0 [0x00559168+758120]
	Ordinal0 [0x0055AA22+764450]
	Ordinal0 [0x00554379+738169]
	Ordinal0 [0x005650D0+807120]
	Ordinal0 [0x005BC402+1164290]
	Ordinal0 [0x005AC5F6+1099254]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/ 20220704_14_33_58.png" target="_blank">
            <img src="../../../../img/ 20220704_14_33_58.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_7' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_005: Modificar el registro</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_7' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_7'>Error</button>
    <div id='div_ft1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_7' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_7'>Error</button>
    <div id='div_ft1_7' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_7: 2022-07-04 14:34:22,839 - root - ERROR - No se encontró el botón Refrescar, revise si el xpath sigue siendo el mismo, para mas detalles del error consulte el reporte
2022-07-04 14:34:22,841 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\report\img  screen：20220704_14_34_22.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\modificarregistro.py", line 22, in modificarregistro
    Refresca2 = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_Refresca)))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563C40+801856]
	Ordinal0 [0x00558932+756018]
	Ordinal0 [0x00559168+758120]
	Ordinal0 [0x0055AA22+764450]
	Ordinal0 [0x00554379+738169]
	Ordinal0 [0x005650D0+807120]
	Ordinal0 [0x005BC402+1164290]
	Ordinal0 [0x005AC5F6+1099254]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\TiposPopup.py", line 58, in test_005
    return modificarregistro.modificarregistro(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\modificarregistro.py", line 33, in modificarregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563C40+801856]
	Ordinal0 [0x00558932+756018]
	Ordinal0 [0x00559168+758120]
	Ordinal0 [0x0055AA22+764450]
	Ordinal0 [0x00554379+738169]
	Ordinal0 [0x005650D0+807120]
	Ordinal0 [0x005BC402+1164290]
	Ordinal0 [0x005AC5F6+1099254]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/ 20220704_14_34_22.png" target="_blank">
            <img src="../../../../img/ 20220704_14_34_22.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_8' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_006: Eliminar el registro creado</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_8' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_8'>Error</button>
    <div id='div_ft1_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_8' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_8'>Error</button>
    <div id='div_ft1_8' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_8: 2022-07-04 14:34:47,187 - root - ERROR - No se encontró el botón Refrescar, revise si el xpath sigue siendo el mismo, para mas detalles del error consulte el reporte
2022-07-04 14:34:47,188 - root - INFO -  Captura: C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\report\img  screen：20220704_14_34_47.png
Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\eliminarregistro.py", line 21, in eliminarregistro
    Refresca3 = self.wait.until(conditions.visibility((By.XPATH, Configuracion.btn_Refresca)))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563C40+801856]
	Ordinal0 [0x00558932+756018]
	Ordinal0 [0x00559168+758120]
	Ordinal0 [0x0055AA22+764450]
	Ordinal0 [0x00554379+738169]
	Ordinal0 [0x005650D0+807120]
	Ordinal0 [0x005BC402+1164290]
	Ordinal0 [0x005AC5F6+1099254]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\TiposPopup.py", line 62, in test_006
    return eliminarregistro.eliminarregistro(self)
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\eliminarregistro.py", line 31, in eliminarregistro
    self.driver.get_screenshot_as_file(img_name)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563C40+801856]
	Ordinal0 [0x00558932+756018]
	Ordinal0 [0x00559168+758120]
	Ordinal0 [0x0055AA22+764450]
	Ordinal0 [0x00554379+738169]
	Ordinal0 [0x005650D0+807120]
	Ordinal0 [0x005BC402+1164290]
	Ordinal0 [0x005AC5F6+1099254]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a  href="../../../../img/ 20220704_14_34_47.png" target="_blank">
            <img src="../../../../img/ 20220704_14_34_47.png" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='ft1_9' class='none'>
    <td class='errorCase' width='300px'><div class='testcase'>test_007: Cerrar_Navegador</div></td>
    <td colspan='5' align='left' width='600px'> <!--print 输出框位置-->
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_9' type="button"  class="btn btn-primary btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_9'>Error</button>
    <div id='div_ft1_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_9' type="button"  class="btn btn-primary btn-xs" data-toggle="collapse" data-target='#div_ft1_9'>Error</button>
    <div id='div_ft1_9' class="collapse in">
    <pre style="overflow-y:scroll; overflow-x:hidden;height:200px; width:600px; margin:auto; border:1px solid #e1e1e1;">
    
ft1_9: Traceback (most recent call last):
  File "C:\xampp\htdocs\Versiones\automatizaciones\AutoPWST\01TPU\testCase\TiposPopup.py", line 66, in test_007
    self.driver.close()
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 937, in close
    self.execute(Command.CLOSE)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Testing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x006B6463+2188387]
	Ordinal0 [0x0064E461+1762401]
	Ordinal0 [0x00563C40+801856]
	Ordinal0 [0x00558932+756018]
	Ordinal0 [0x0054C2F0+705264]
	Ordinal0 [0x005B2C40+1125440]
	Ordinal0 [0x005AC7A3+1099683]
	Ordinal0 [0x00586BE0+945120]
	Ordinal0 [0x00587AD6+948950]
	GetHandleVerifier [0x009571F2+2712546]
	GetHandleVerifier [0x0094886D+2652765]
	GetHandleVerifier [0x0074002A+520730]
	GetHandleVerifier [0x0073EE06+516086]
	Ordinal0 [0x0065468B+1787531]
	Ordinal0 [0x00658E88+1805960]
	Ordinal0 [0x00658F75+1806197]
	Ordinal0 [0x00661DF1+1842673]
	BaseThreadInitThunk [0x7581FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76FF7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76FF7A6E+238]



    </pre>
    </div>
    </td>
    <td align="right">
        <a hidden="hidden" href="" target="_blank">
            <img src="" height="200px" width="400px"/>
        </a>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>Caso de prueba</td>
    <td>9</td>
    <td>1</td>
    <td>0</td>
    <td>8</td>
    <td>Taza de resultado：11.11%</td>
    <td> <a href="" target="_blank"></a></td>
</tr>
</table>

<div id='ending'> </div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
